= Hacking OpenJDK: Hurra, ich habe Java schneller gemacht!
Markus Karg (Head Crashing Informatics) <markus@headcrashing.eu>
v1.0, 2023-12-11: Rohentwurf

// Die folgenden Attribute darfst Du NICHT verändern:
:doctype: article
:table-caption: Tabelle
:listing-caption: Listing
:figure-caption: Abbildung
:source-language: java
:source-indent: no
:source-highlighter: rouge
:reproducible:

// Die folgenden Attribute darfst Du gerne anpassen:
:imagesdir: .

[abstract]
Machmal muss man ungewöhnliche Wege gehen, um seine Anwendung zu beschleunigen. In meinem Fall war es der Umbau des I/O-Subsystems in OpenJDK.


== Wie alles begann

Vor einigen Jahren bemerkte ich, dass mein Maven-Build sehr langsam war, und das störte mein Team sehr. Schnell war als Ursache die Menge und Größe der von uns verwendeten Dateien ausgemacht, denn unser Projekt sehr hatte viele und sehr große Dateien. Seltsamerweise schien Maven sie in den Hauptspeicher zu laden, obwohl sie keines Processings bedürfen (beispielsweise beim "Download" aus dem lokalen Repository). Eine Prüfung des Quellcodes von Maven (genau genommen von dessen I/O-Bibliothek aus dem Plexus-Projekt) zeigte, dass Maven zum Kopieren eine Schleife über ein Paar an InputStream und OutputStream benutzte. Eine Schleife, wie wir sie alle schon zigfach geschrieben hatten in den letzten Dekaden.

Als versierter Open-Source-Contributor sandte ich einen Pull Request ein, der die Schleife durch den seit Java 9 existierenden Befehl InputStream.transferTo(OutputStream) ersetzte. Meine Hoffnung war, dass OpenJDK die Methode nicht nur als "Syntactic Sugar" anbot, sondern sie in irgend einer Art und Weise performancetechnisch optimiert.

Wie ein auf Wunsch des Maven-Teams durchgeführter JMH-Benchmark zeige, war dem leider nicht so. Maven war genauso langsam wir vorher. Also grub ich noch ein paar Schichten tiefer und fand zu meinem Erschrecken im Quellcode von OpenJDK die gleiche simple Schleife, die ich kurz vorher aus Maven ausgebaut hatte. Um die Performance 
Nun folgt der eigentliche Artikeltext. Bitte schreibe im Fließtext und gebe die Zeilenschaltung nur am Ende eines Absatzes ein. Zwischen Absätzen verwende bitte eine Leerzeile. Die automatische Trennung bitte ausschalten.

Text kann je nach Bedarf *fett* oder _kursiv_ oder *_fett und kursiv_* formatiert werden. Befehle oder ähnliches im Fliesstext können in `Monospace` geschrieben werden.


== Hot Spot identifizieren, Lösung entwickeln


== Konstruktion


== Implementierung


== Erfolg


== Ausblick

Weitere Ideen für die Zukunft-


[bibliography]
== Quellen

- [[[TestQuelle,1]]] Autor(in) (Jahr): Titel. Verlag, Ort
- [[[JavaAktuell,2]]] Java aktuell Website: link:https://www.ijug.eu/de/java-aktuell/zeitschrift/[]


== Über den Autoren/die Autorin

...
